# backend/app/db/models.py
# Database table definitions using SQLAlchemy
# Defines the structure of all tables in the database
#
# Day 48: Added image_caption column for vision model output
#
# IMPORTANT: If you already have a models.py file, you only need to
# ADD the image_caption column line. The rest of your file stays the same.
# Look for the comment "# NEW - Day 48" below.
#
# If your file looks different from this, just add this ONE line
# to your existing incidents table definition:
#
#   Column("image_caption", String, nullable=True),
#

# Import SQLAlchemy components for defining table structure
import sqlalchemy

# Import individual column types we need
from sqlalchemy import (
    Table,          # Represents a database table
    Column,         # Represents a column in a table
    Integer,        # Integer data type (for IDs, counts)
    String,         # Text/string data type
    Float,          # Decimal number type (for risk scores)
    DateTime,       # Date and time type
    MetaData,       # Container that holds table definitions together
)

# Import datetime for setting default timestamps
from datetime import datetime


# ========================================
# METADATA
# ========================================

# MetaData is a container that holds all table definitions
# It's used by SQLAlchemy to know about the database structure
# We'll pass this to the database engine to create tables
metadata = sqlalchemy.MetaData()


# ========================================
# INCIDENTS TABLE
# ========================================

# Define the incidents table structure
# Each row represents one incident report
# This table is the core of the entire application
incidents = Table(
    "incidents",    # Table name in the database
    metadata,       # Register this table with our metadata

    # --- Core fields (from Day 8-10) ---

    # Primary key - unique identifier for each incident
    # autoincrement=True means the database automatically assigns 1, 2, 3...
    Column("id", Integer, primary_key=True, autoincrement=True),

    # Source of the incident report (e.g., "citizen", "dispatcher", "sensor")
    # nullable=True means this field is optional
    Column("source", String, nullable=True),

    # Text description of what happened
    # This is the main content the citizen provides
    Column("description", String, nullable=False),

    # Location where the incident occurred (address or coordinates)
    Column("location", String, nullable=True),

    # When the incident was created in the database
    # default=datetime.utcnow sets this automatically when a row is inserted
    Column("created_at", DateTime, default=datetime.utcnow),

    # --- File upload fields (from Day 17) ---

    # Path to uploaded audio file on disk (e.g., "backend/app/media/tmp/audio/abc.wav")
    # NULL if no audio was uploaded
    Column("audio_path", String, nullable=True),

    # Path to uploaded image file on disk
    # NULL if no image was uploaded
    Column("image_path", String, nullable=True),

    # --- AI-generated fields ---

    # Audio transcript from Whisper ASR (Day 34)
    # Generated by transcribe_audio() in asr.py
    # NULL if no audio was uploaded or transcription failed
    Column("transcript", String, nullable=True),

    # AI-generated summary from BART-Large-CNN (Day 47)
    # Generated by summarize_text() in summarizer.py
    Column("summary", String, nullable=True),

    # Risk score from BART-MNLI zero-shot classification (Day 45)
    # Float between 0.0 (routine) and 1.0 (critical emergency)
    # Generated by calculate_risk_score() in risk_scorer.py
    Column("risk_score", Float, nullable=True),

    # Incident type from BART-MNLI zero-shot classification (Day 46)
    # Values: "fire", "medical", "traffic", "crime", "noise", "infrastructure", "other"
    # Generated by classify_incident() in text_classifier.py
    Column("incident_type", String, nullable=True),

    # Severity level from BART-MNLI zero-shot classification (Day 46)
    # Values: "high", "medium", "low"
    # Generated by classify_incident() in text_classifier.py
    Column("severity", String, nullable=True),

    # NEW - Day 48: Image caption from BLIP vision model
    # Text description of the uploaded image contents
    # Generated by analyze_image() in image_analyzer.py
    # NULL if no image was uploaded or analysis failed
    Column("image_caption", String, nullable=True),
)