# backend/app/db/models.py
# This file defines the database table structure for incidents
# It tells SQLAlchemy what columns exist and their data types

# Import SQLAlchemy core components
from sqlalchemy import (
    DateTime,
    Table,      # Represents a database table
    Column,     # Represents a column in a table
    Integer,    # Integer data type
    String,     # Variable-length string data type
    Float,      # Floating-point number data type
    Text,       # Long text data type
)

# Import metadata so this table gets registered
from app.db.database import metadata


# Define the incidents table
# This maps directly to a SQL table in the database
incidents = Table(
    "incidents",  # Table name in the database
    metadata,      # Links this table to the shared metadata
    
    # ========================================
    # PRIMARY KEY
    # ========================================
    # Unique identifier for each incident
    # Auto-increments with each new row
    Column("id", Integer, primary_key=True, autoincrement=True),
    
    # ========================================
    # CORE INCIDENT FIELDS
    # ========================================
    
    # Who/what reported this incident
    # Examples: "citizen", "dispatcher", "sensor", "police"
    # Required field (cannot be NULL)
    Column("source", String(100), nullable=False),
    
    # Human-written description of what happened
    # Examples: "Car accident on Main St", "Fire reported"
    # Required field
    Column("description", Text, nullable=False),
    
    # Where the incident occurred
    # Examples: "123 Main St", "Downtown intersection"
    # Required field
    Column("location", String(255), nullable=False),
    
    # ========================================
    # MEDIA PATHS (Optional)
    # ========================================
    
    # File path to uploaded audio recording
    # Example: "uploads/audio/abc-123.wav"
    # Optional - nullable=True means it can be NULL
    Column("audio_path", String(500), nullable=True),
    
    # File path to uploaded image
    # Example: "uploads/images/def-456.jpg"
    # Optional
    Column("image_path", String(500), nullable=True),
    
    # ========================================
    # AI-GENERATED FIELDS (Optional)
    # ========================================
    
    # AI-generated text transcript from audio
    # Generated by ASR (Automatic Speech Recognition) model
    # Optional - populated after processing
    Column("transcript", Text, nullable=True),
    
    # AI-generated summary of the incident
    # Generated by summarization model
    # Optional - populated after processing
    Column("summary", Text, nullable=True),
    
    # AI-generated risk score (0.0 to 1.0)
    # Higher score = higher urgency/risk
    # Examples: 0.2 (low), 0.5 (medium), 0.9 (high)
    # Optional - populated after processing
    Column("risk_score", Float, nullable=True),
    
    # AI-generated incident type classification
    # Examples: "medical", "fire", "traffic", "crime"
    # Optional - populated after processing
    Column("incident_type", String(100), nullable=True),
    
    # AI-generated severity level
    # Examples: "low", "medium", "high", "critical"
    # Optional - populated after processing
    Column("severity", String(50), nullable=True),

    Column("image_description", Text, nullable=True),


    Column("status", String(50), nullable=True, default="pending"),

    Column("created_at", DateTime, nullable=True),
)


# Note on nullable:
# - nullable=False means the field is REQUIRED (NOT NULL in SQL)
# - nullable=True means the field is OPTIONAL (can be NULL)
# - Default is nullable=True if not specified