# backend/app/routes/incidents.py
# This file contains all incident-related API endpoints
# Routes are organized here and registered in main.py

# Import FastAPI routing components
from fastapi import APIRouter, UploadFile, File, HTTPException, Depends, BackgroundTasks
from typing import Optional

# Import database dependency
from databases import Database
from app.db.dependencies import get_db

# Import database models
from app.db.models import incidents

# Import Pydantic schemas for request/response validation
from app.schemas.incident import (
    IncidentCreate,
    IncidentRead,
    IncidentUpdate
)

# Import utility functions
from app.utils.file_utils import save_upload_file

# Import services for AI processing
from app.services.incident_processor import process_incident


# ========================================
# CREATE ROUTER
# ========================================
# Router groups related endpoints together
router = APIRouter()


# ========================================
# CREATE INCIDENT
# ========================================

@router.post("/incidents", response_model=IncidentRead, status_code=201)
async def create_incident(
    incident: IncidentCreate,
    background_tasks: BackgroundTasks,
    db: Database = Depends(get_db)
):
    """
    Create a new incident report.
    
    Steps:
    1. Validate incoming data (automatically done by Pydantic)
    2. Insert incident into database
    3. Schedule background AI processing
    4. Return created incident with ID
    
    Background processing includes:
    - Audio transcription (if audio present)
    - Text classification
    - Risk scoring
    - Summary generation
    """
    
    # Build INSERT query
    query = incidents.insert().values(
        source=incident.source,
        description=incident.description,
        location=incident.location,
        audio_path=None,      # Set later when audio uploaded
        image_path=None,      # Set later when image uploaded
        transcript=None,      # Generated by AI
        summary=None,         # Generated by AI
        risk_score=None,      # Generated by AI
        incident_type=None,   # Generated by AI
        severity=None         # Generated by AI
    )
    
    # Execute query and get auto-generated ID
    incident_id = await db.execute(query)
    
    # Schedule background processing (Day 16 requirement)
    # This runs after the response is sent to the client
    background_tasks.add_task(
        process_incident,
        incident_id=incident_id,
        log_message=f"Processing incident {incident_id}"
    )
    
    # Return the created incident
    return {
        "id": incident_id,
        "source": incident.source,
        "description": incident.description,
        "location": incident.location,
        "audio_path": None,
        "image_path": None,
        "transcript": None,
        "summary": None,
        "risk_score": None,
        "incident_type": None,
        "severity": None
    }


# ========================================
# LIST INCIDENTS (with filtering)
# ========================================

@router.get("/incidents", response_model=list[IncidentRead])
async def list_incidents(
    db: Database = Depends(get_db),
    source: Optional[str] = None,
    incident_type: Optional[str] = None,
    severity: Optional[str] = None,
    min_risk_score: Optional[float] = None,
    limit: int = 10,
    offset: int = 0,
    sort_by: str = "id",
    order: str = "desc"
):
    """
    List incidents with optional filtering and pagination.
    
    Query parameters:
    - source: Filter by incident source (e.g., "citizen")
    - incident_type: Filter by type (e.g., "fire", "medical")
    - severity: Filter by severity (e.g., "high")
    - min_risk_score: Only show incidents with risk >= this value
    - limit: Number of results to return (default 10)
    - offset: Number of results to skip (default 0)
    - sort_by: Field to sort by (default "id")
    - order: Sort order "asc" or "desc" (default "desc")
    """
    
    # Start with base SELECT query
    query = incidents.select()
    
    # Apply filters if provided
    if source:
        query = query.where(incidents.c.source == source)
    
    if incident_type:
        query = query.where(incidents.c.incident_type == incident_type)
    
    if severity:
        query = query.where(incidents.c.severity == severity)
    
    if min_risk_score is not None:
        query = query.where(incidents.c.risk_score >= min_risk_score)
    
    # Apply sorting
    sort_column = getattr(incidents.c, sort_by, incidents.c.id)
    if order.lower() == "desc":
        query = query.order_by(sort_column.desc())
    else:
        query = query.order_by(sort_column.asc())
    
    # Apply pagination
    query = query.limit(limit).offset(offset)
    
    # Execute query and return results
    results = await db.fetch_all(query)
    return results


# ========================================
# GET SINGLE INCIDENT
# ========================================

@router.get("/incidents/{incident_id}", response_model=IncidentRead)
async def get_incident(
    incident_id: int,
    db: Database = Depends(get_db)
):
    """
    Get a specific incident by ID.
    Returns 404 if incident not found.
    """
    
    # Build SELECT query for specific incident
    query = incidents.select().where(incidents.c.id == incident_id)
    
    # Execute query
    incident = await db.fetch_one(query)
    
    # Return 404 if not found
    if incident is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    return incident


# ========================================
# UPDATE INCIDENT
# ========================================

@router.patch("/incidents/{incident_id}", response_model=IncidentRead)
async def update_incident(
    incident_id: int,
    incident_update: IncidentUpdate,
    db: Database = Depends(get_db)
):
    """
    Update specific fields of an incident.
    Only provided fields are updated (partial update).
    """
    
    # Check if incident exists
    query = incidents.select().where(incidents.c.id == incident_id)
    existing = await db.fetch_one(query)
    
    if existing is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    # Build dictionary of fields to update (exclude None values)
    update_data = incident_update.dict(exclude_unset=True)
    
    if not update_data:
        # Nothing to update
        return existing
    
    # Build UPDATE query
    update_query = (
        incidents
        .update()
        .where(incidents.c.id == incident_id)
        .values(**update_data)
    )
    
    # Execute update
    await db.execute(update_query)
    
    # Fetch and return updated incident
    updated = await db.fetch_one(
        incidents.select().where(incidents.c.id == incident_id)
    )
    return updated


# ========================================
# DELETE INCIDENT
# ========================================

@router.delete("/incidents/{incident_id}")
async def delete_incident(
    incident_id: int,
    db: Database = Depends(get_db)
):
    """
    Delete an incident by ID.
    Returns 404 if incident not found.
    """
    
    # Check if exists
    query = incidents.select().where(incidents.c.id == incident_id)
    existing = await db.fetch_one(query)
    
    if existing is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    # Delete the incident
    delete_query = incidents.delete().where(incidents.c.id == incident_id)
    await db.execute(delete_query)
    
    return {
        "message": f"Incident {incident_id} deleted successfully",
        "incident_id": incident_id
    }


# ========================================
# UPLOAD AUDIO FILE
# ========================================

@router.post("/incidents/{incident_id}/audio")
async def upload_audio(
    incident_id: int,
    file: UploadFile = File(...),
    background_tasks: BackgroundTasks = None,
    db: Database = Depends(get_db)
):
    """
    Upload audio file for an incident.
    Saves file to disk and updates incident record.
    Triggers background transcription.
    """
    
    # Check if incident exists
    query = incidents.select().where(incidents.c.id == incident_id)
    incident = await db.fetch_one(query)
    
    if incident is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    # Save the uploaded file
    file_path = save_upload_file(file, subfolder="audio")
    
    # Update incident with audio path
    update_query = (
        incidents
        .update()
        .where(incidents.c.id == incident_id)
        .values(audio_path=file_path)
    )
    await db.execute(update_query)
    
    # Trigger reprocessing in background to generate transcript
    if background_tasks:
        background_tasks.add_task(
            process_incident,
            incident_id=incident_id,
            log_message=f"Transcribing audio for incident {incident_id}"
        )
    
    return {
        "message": "Audio uploaded successfully",
        "audio_path": file_path,
        "incident_id": incident_id
    }


# ========================================
# UPLOAD IMAGE FILE
# ========================================

@router.post("/incidents/{incident_id}/image")
async def upload_image(
    incident_id: int,
    file: UploadFile = File(...),
    background_tasks: BackgroundTasks = None,
    db: Database = Depends(get_db)
):
    """
    Upload image file for an incident.
    Saves file to disk and updates incident record.
    Triggers background image analysis.
    """
    
    # Check if incident exists
    query = incidents.select().where(incidents.c.id == incident_id)
    incident = await db.fetch_one(query)
    
    if incident is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    # Save the uploaded file
    file_path = save_upload_file(file, subfolder="images")
    
    # Update incident with image path
    update_query = (
        incidents
        .update()
        .where(incidents.c.id == incident_id)
        .values(image_path=file_path)
    )
    await db.execute(update_query)
    
    # Trigger reprocessing in background for image analysis
    if background_tasks:
        background_tasks.add_task(
            process_incident,
            incident_id=incident_id,
            log_message=f"Analyzing image for incident {incident_id}"
        )
    
    return {
        "message": "Image uploaded successfully",
        "image_path": file_path,
        "incident_id": incident_id
    }


# ========================================
# MANUAL PROCESSING TRIGGER
# ========================================

@router.post("/incidents/{incident_id}/process")
async def process_incident_endpoint(
    incident_id: int,
    background_tasks: BackgroundTasks,
    db: Database = Depends(get_db)
):
    """
    Manually trigger AI processing for an incident.
    Useful for reprocessing or if background task failed.
    """
    
    # Check if incident exists
    query = incidents.select().where(incidents.c.id == incident_id)
    incident = await db.fetch_one(query)
    
    if incident is None:
        raise HTTPException(
            status_code=404,
            detail=f"Incident {incident_id} not found"
        )
    
    # Schedule processing
    background_tasks.add_task(
        process_incident,
        incident_id=incident_id,
        log_message=f"Manual processing triggered for incident {incident_id}"
    )
    
    return {
        "status": "processing",
        "message": f"AI processing started for incident {incident_id}",
        "incident_id": incident_id
    }