# backend/app/schemas/incident.py
# This file defines Pydantic models for incident data validation
# Pydantic ensures data coming in/out of API matches expected structure

# Import BaseModel - the base class for all Pydantic models
from pydantic import BaseModel

# Import Optional type for fields that may be None
from typing import Optional
from datetime import datetime


# ========================================
# BASE MODEL
# ========================================

class IncidentBase(BaseModel):
    """
    Base incident model with core fields.
    Shared by both Create and Read models.
    """
    source: str
    description: str
    location: str


# ========================================
# CREATE MODEL (Request Body)
# ========================================

class IncidentCreate(IncidentBase):
    """
    Model for creating a new incident.
    Used in POST /incidents endpoint.
    
    Only includes fields the user provides.
    Does NOT include:
    - id (auto-generated by database)
    - AI-generated fields (filled later)
    """
    pass  # Inherits all fields from IncidentBase


# ========================================
# UPDATE MODEL (Optional Updates)
# ========================================

class IncidentUpdate(BaseModel):
    """
    Model for updating an incident.
    All fields are optional - only update what's provided.
    Used in PATCH /incidents/{id} endpoint.
    """
    source: Optional[str] = None
    description: Optional[str] = None
    location: Optional[str] = None
    audio_path: Optional[str] = None
    image_path: Optional[str] = None
    transcript: Optional[str] = None
    summary: Optional[str] = None
    risk_score: Optional[float] = None
    incident_type: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    image_description: Optional[str] = None
    created_at: Optional[datetime] = None


# ========================================
# READ MODEL (Response Body)
# ========================================

class IncidentRead(IncidentBase):
    """
    Model for reading incident data from database.
    Used in GET /incidents and GET /incidents/{id} responses.
    
    Includes ALL fields from database table.
    """
    
    # Auto-generated ID from database
    id: int
    
    # Media file paths (optional - may be None)
    audio_path: Optional[str] = None
    image_path: Optional[str] = None
    
    # AI-generated fields (optional - populated after processing)
    transcript: Optional[str] = None
    summary: Optional[str] = None
    risk_score: Optional[float] = None
    incident_type: Optional[str] = None
    severity: Optional[str] = None
    status: Optional[str] = None
    image_description: Optional[str] = None
    created_at: Optional[datetime] = None
    image_description: str | None = None

    
    class Config:
        """
        Pydantic configuration.
        from_attributes=True allows creating model from ORM objects.
        """
        from_attributes = True


# ========================================
# FILTER MODEL (Query Parameters)
# ========================================

class IncidentFilter(BaseModel):
    """
    Model for filtering incidents in list endpoint.
    Used as query parameters in GET /incidents.
    """
    
    # Filter by source
    source: Optional[str] = None
    
    image_description: str | None = None

    # Filter by incident type
    incident_type: Optional[str] = None
    
    # Filter by severity
    severity: Optional[str] = None
    status: Optional[str] = None
    image_description: Optional[str] = None
    created_at: Optional[datetime] = None
    
    # Minimum risk score (e.g., only show incidents with risk >= 0.5)
    min_risk_score: Optional[float] = None
    
    # Pagination - how many results to return
    limit: int = 10
    
    # Pagination - how many results to skip
    offset: int = 0
    
    # Sorting field
    sort_by: str = "id"
    
    # Sort order: "asc" or "desc"
    order: str = "desc"

    