# This file is about “What does my data look like in the database?”

<<<<<<< HEAD
# Import SQlAlchemy column types
from sqlalchemy import Table, Column, Integer, String, Float

# Import metadata so this table gets registered
# .database in Python is a form of relative import, which allows you to import modules or packages located within the same package structure as the current file
=======

# SQLAlchemy imports for defining tables
from sqlalchemy import Table, Column, Integer, String, Text, DateTime, Float, func



from sqlalchemy.sql import func # For timestamps


# Import metadata so this table gets registered
# This is the registry where all tables are registered 
# database in Python is a form of relative import, which allows you to import modules or packages located within the same package structure as the current file
>>>>>>> 585adbd (Day 12: Integrated FastAPI with PostgreSQL, moved backend to main repo)
from app.db.database import metadata

# Define a table called "incidents"
# This maps directly to a SQL table
<<<<<<< HEAD

incidents = Table(
    "incidents",            # table name
    metadata,               # metadata object
    Column("id", Integer, primary_key=True),   # unique id
    Column("description", String, nullable=False), # description text
    Column("location", String, nullable=False),    # location text
    Column("source", String, nullable=False),      # source of report
    Column("risk_score", Float, nullable=True),   # optional AI-calculated risk
    Column("transcript", String, nullable=True),  # optional audio transcript
    Column("summary", String, nullable=True),     # optional AI summary
=======
# Each row in this table represents a single incident report 

incidents = Table(
    "incidents",            # table name in the database
    metadata,               # link table to metadata registry
    
    Column("id", Integer, primary_key=True, index=True),
    # "id" -> the unique identifier for each incident 
    # primary_key=True -> automatically unique 
    # index=True -> creates an index for faster searches

    Column("title", String(255), nullable=False),
    # title -> short title for the incident 
    # String(255) -> max 255 characters
    # nullable=False -> required 


    Column("description", Text, nullable=True),
    # description -> longer text for details
    # nullable=True -> optional field 

#
    Column("location", String(255), nullable=True),
    # location of incident 



    Column("source", String(50), nullable=True),

    Column("risk_score", Float, nullable=True),
    # Numeric risk score generated by ML models (0–1 or 0–100)

    Column("transcript", Text, nullable=True),
    # Full transcription of 911 call or voice message

    Column("summary", Text, nullable=True),
    # AI-generated summary of call, text, or images

    Column("created_at", DateTime(timezone=True), server_default=func.now()),
    # created_at -> timestamp when incident was created
    # func.now() -> automatically uses current time in database

    Column("updated_at", DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    # updated_at -> timestamp when incident is updated
    # onupdate=func.now() -> updates automatically whenever row changes
    
>>>>>>> 585adbd (Day 12: Integrated FastAPI with PostgreSQL, moved backend to main repo)
)

 # NULL means no value, missing, etc.
    # nullable=False prevents NULL, but does NOT prevent empty strings

